### ISSUE TITLE
Add lidar filtering and clustering method

### ISSUE THREAD

**Issue by airfield20** [iscumd/obstacle_detection#5]

**Comment by airfield20** [comment]
The filtering method should input a RectangleBoundary object as a parameter and output an std::vector<Point>. Only points within the boundary should be returned.

**Comment by airfield20** [comment]
It would be cool to try implementing a clustering algorithm like k-means. If it proves too difficult or time consuming then using the approach from last year will suffice for now. However if you choose to do that, I think a quality clustering algorithm will end up on our todo list in the near term.

**Comment by airfield20** [comment]
Also please branch off of this repo, not a forked version of it. Create a pull request when its complete and builds.

**Comment by davidcutting** [comment]
I was looking into k-means. I will probably be using that.
